version: '3.5'
services:
 postgres:
  container_name: postgres
  networks:
   - default  
  volumes:
   - c:\postgres:/var/lib/postgresql/data #windows setup
   #- /var/postgres/:/var/lib/postgresql/data #linux setup
  image: postgres:15
  restart: always
  ports:
   - 5432:5432
  environment:
   POSTGRES_PASSWORD: 'Guatemala1'
   POSTGRES_USER: postgres
   
 backend:
  image: ng-backend-chemita
  build:
   context: .
   dockerfile: Dockerfile
  restart: always
  ports:
   - 3000:3000 
  networks:
   - default
  depends_on:
   - postgres
   #https://stackoverflow.com/questions/61578005/nodejs-14-in-a-docker-container-cant-connect-to-postgres-db-in-out-docker
   
networks:
  default: