version: '3.5'
services:
 backend:
  image: node:19
  volumes:
   - c:\angular\chems\backend:/backend #windows setup
   #- /chems/backend:/backend #linux setup
  restart: always
  ports:
   - 3000:3000

