version: '3.5'
services:
 postgresql:
  volumes:
   - c:\postgres:/var/lib/postgresql/data #windows setup
   #- /var/postgres/:/var/lib/postgresql/data #linux setup
  image: postgres:15.1
  restart: always
  ports:
   - 5432:5432
  environment:
   POSTGRES_PASSWORD: 'Guatemala1'

